---
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: anrayliu/url-shortener-backend:latest
    ports:
      - ${API_PORT}:${API_PORT}
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "timeout 5 bash -c 'echo -n > /dev/tcp/127.0.0.1/${API_PORT}' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 3
      start_period: 15s
    restart: on-failure

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: anrayliu/url-shortener-frontend:latest
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    env_file: .env
    depends_on:
      backend:
        condition: service_healthy
    restart: on-failure

  database:
    build:
      context: .
      dockerfile: backend/database/Dockerfile
    image: anrayliu/url-shortener-database:latest
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 40s
    restart: on-failure

  metrics:
    image: prom/prometheus:v3.9.1
    depends_on:
      backend:
        condition: service_healthy

  dashboard:
    image: grafana/grafana:12.4.0-20836657505-ubuntu
    ports:
      - ${DASHBOARD_PORT}:${DASHBOARD_PORT}
    depends_on: [metrics]
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_PASSWORD}
