global:
  scrape_interval: 10s

scrape_configs:
  - job_name: backend
    static_configs:
      - targets: [backend:9100] # not a secret, fine for version control

  - job_name: prometheus
    static_configs:
      - targets: [metrics:9090] # not a secret, fine for version control
