---
name: image scans

on:
  workflow_call:
    inputs:
      verticals:
        required: true
        type: string

jobs:
  trivy-scan:
    name: Trivy Vulnerability Scan for ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ${{ fromJSON(inputs.verticals) }}

    steps:
      - name: Security Scan Image ${{ matrix.image }}
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: docker.io/anrayliu/${{ matrix.image }}:latest
          severity: "CRITICAL"
          ignore-unfixed: true
          exit-code: 1

  generate-sbom:
    name: Generate SBOM for ${{ matrix.image }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image: ${{ fromJSON(inputs.verticals) }}

    steps:
      - name: SBOM creation for ${{ matrix.image }}
        uses: anchore/sbom-action@v0
        with:
          image: docker.io/anrayliu/${{ matrix.image }}:latest

      - name: Print output for ${{ matrix.image }}
        run: cat sbom.spdx.json