---
name: nightly scans

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  image-scan:
    uses: ./.github/workflows/image_scan.yaml
    with:
      verticals: '["url-shortener-backend", 
                   "url-shortener-frontend",
                   "url-shortener-database"]'