---
name: CI Nightly Scans

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  nightly-trivy-scan:
    uses: ./.github/workflows/trivy_scan.yaml
    with:
      verticals: '["url-shortener-backend", 
                   "url-shortener-frontend",
                   "url-shortener-database"]'